# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c956606897f9ea0e92ad51ca4cb68b857435d5ea3a00b738b40d3848e555c8a73beb06f311c7658d57c9d768882e64cb4af52f8a15b76edbfeb564402f3b2d5a

test:
  secret_key_base: 3f582405e0ef87b8785b36b71e0bc6357e187ec5ec0545236e48537c859c9c0e883247c48f4ef88c98baf7877131c7ae8fa68824b2acf1b01df0daddb231e923

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
